# Generated by Django 2.1.4 on 2018-12-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField()),
                ('left', models.FloatField()),
                ('bottom', models.FloatField()),
                ('right', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TreatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='imagerect',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treated_image.TreatedImage'),
        ),
    ]
