# Generated by Django 2.1.5 on 2019-01-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField()),
                ('left', models.FloatField()),
                ('bottom', models.FloatField()),
                ('right', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TreatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('path', models.TextField()),
                ('rects', models.ManyToManyField(to='treated_image.ImageRect')),
            ],
        ),
    ]
