# Generated by Django 2.1.5 on 2019-01-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treated_image', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatedimage',
            old_name='url',
            new_name='link',
        ),
    ]
