# Generated by Django 2.1.4 on 2018-12-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treated_image', '0002_auto_20181214_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerect',
            name='image',
        ),
        migrations.AddField(
            model_name='treatedimage',
            name='rects',
            field=models.ManyToManyField(to='treated_image.ImageRect'),
        ),
    ]
